# -*- coding: utf-8 -*-
"""Project3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ZKh7DOqFz2a9sEoQafiB8TSiLR-5Opa
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('/content/Electric_Vehicle_Population_Data.csv')

print(data.head())
print(data.describe())
print(data.info())

# Check available column names
print(data.columns)

# Define the categorical and numeric columns
categorical_columns = ['State', 'Make', 'Electric Vehicle Type']
numeric_columns = ['Electric Range', 'Base MSRP']

# Check unique values in categorical columns
for col in categorical_columns:
    unique_values = data[col].unique()
    print(f"Unique values in {col}: {unique_values}")

# Visualizations for numeric columns
for col in numeric_columns:
    plt.figure(figsize=(8, 6))
    plt.hist(data[col], bins=20, edgecolor='black')
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.grid(True)
    plt.show()

# Bar charts for categorical columns
for col in categorical_columns:
    plt.figure(figsize=(8, 6))
    data[col].value_counts().plot(kind='bar')
    plt.title(f'{col} Distribution')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.grid(axis='y')
    plt.show()

# Scatter plot for Electric Range vs. Base MSRP
plt.figure(figsize=(8, 6))
plt.scatter(data['Electric Range'], data['Base MSRP'], alpha=0.5)
plt.title('Electric Range vs. Base MSRP')
plt.xlabel('Electric Range')
plt.ylabel('Base MSRP')
plt.grid(True)
plt.show()